-- USE private_school;

-- ** INSERT STUDENTS **--
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('ANGELOS', 'ANGELOU', '1988-11-21');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('ALEXIOS', 'ALEXIOU', '1983-02-04');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('GRIGORIOS', 'GRIGORIOU', '1979-07-06');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('PETROS', 'PETROU', '1991-05-08');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('ANASTASIOS', 'ANASTASIOU', '1987-09-02');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('GEORGIOS', 'GEORGIOU', '1988-11-13');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('DIMITRIOS', 'DIMITRIOU', '1996-12-21');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('PANAGIOTIS', 'PANAGIOTOU', '1989-06-30');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('SPIROS', 'SPIROU', '1993-10-06');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('ALEXANDROS', 'ALEXANDROU', '1993-03-11');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('IORDANIS', 'IORDANIDIS', '1984-08-19');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('STELIOS', 'STILIANOU', '1997-07-10');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('ANDREAS', 'ANDREOPOULOS', '1992-07-12');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('LEFTERIS', 'ELEFTHERIOU', '1988-09-26');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('THEODOROS', 'THEODORIDIS', '1988-09-26');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('MICHALIS', 'MICHAIL', '1986-04-09');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('STEFANOS', 'STEFANIDIS', '1990-01-05');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('APOSTOLOS', 'APOSTOLOU', '1987-08-18');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('THOMAS', 'THOMOPOULOS', '1992-11-03');
INSERT INTO STUDENT (FIRSTNAME, LASTNAME, DATEOFBIRTH) VALUES ('CHARALAMBOS', 'CHARALAMBOUS', '1986-10-26');

-- DIORTHOSI STOIXEION STIN EISAGOGI
-- DELETE FROM STUDENT WHERE STUDENT_ID=1;
-- ALTER TABLE STUDENT AUTO_INCREMENT = 1;

-- ** INSERT COURSES **--
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB8', 'JAVA', 'FULL TIME', '2019-01-01', '2019-03-31');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB8', 'JAVA', 'PART TIME', '2019-01-01', '2019-06-30');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB8', 'C#', 'FULL TIME', '2019-01-01', '2019-03-31');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB8', 'C#', 'PART TIME', '2019-01-01', '2019-06-30');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB9', 'JAVA', 'FULL TIME', '2019-07-01', '2019-09-30');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB9', 'JAVA', 'PART TIME', '2019-07-01', '2019-12-31');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB9', 'C#', 'FULL TIME', '2019-07-01', '2019-07-01');
INSERT INTO COURSE (TITLE, STREAM, CO_TYPE, START_DATE, END_DATE) VALUES ('CB9', 'C#', 'PART TIME', '2019-07-01', '2019-12-31');

-- DIORTHOSI STOIXEION STIN EISAGOGI
-- DELETE FROM COURSE WHERE COURSE_ID=9;
-- ALTER TABLE COURSE AUTO_INCREMENT = 7;

-- ** INSERT TRAINERS **--
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('ROBERT', 'MACKIN');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('PAUL', 'RALPH');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('TOM', 'SMITH');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('JONATHAN', 'PERLY');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('IAN', 'CALLAGHAN');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('JOHN', 'TYLER');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('TOMMY', 'LOREN');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('SERGIO', 'PHANEL');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('MICHAEL', 'SMORA');
INSERT INTO TRAINER (FIRSTNAME, LASTNAME) VALUES ('ANATOLY', 'PESKOV');

-- DIORTHOSI STOIXEION STIN EISAGOGI
-- DELETE FROM STUDENT_COURSE WHERE ST_CO_ID=2;
-- ALTER TABLE STUDENT_COURSE AUTO_INCREMENT = 1;

-- ** INSERT ASSIGNMENTS **--
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST JAVA ASSIGNMENT', '2019-01-15 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND JAVA ASSIGNMENT', '2019-01-29 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'JAVADB CONNECTOR ASSIGNMENT', '2019-02-12 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST JAVA-FRONT-END ASSIGNMENT', '2019-02-26 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND JAVA-FRONT-END ASSIGNMENT', '2019-03-13 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING JAVA WITH DATABASE', '2019-02-15 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'JAVA TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-03-29 20:00:00', 1);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST JAVA ASSIGNMENT', '2019-01-29 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND JAVA ASSIGNMENT', '2019-02-27 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'JAVADB CONNECTOR ASSIGNMENT', '2019-03-26 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST JAVA-FRONT-END ASSIGNMENT', '2019-04-16 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND JAVA-FRONT-END ASSIGNMENT', '2019-05-28 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING JAVA WITH DATABASE', '2019-04-03 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'JAVA TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-06-26 20:00:00', 2);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST C# ASSIGNMENT', '2019-01-15 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND C# ASSIGNMENT', '2019-01-29 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'C#DB CONNECTOR ASSIGNMENT', '2019-02-12 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST C#-FRONT-END ASSIGNMENT', '2019-02-26 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND C#-FRONT-END ASSIGNMENT', '2019-03-13 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING C# WITH DATABASE', '2019-02-15 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'C# TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-03-29 20:00:00', 3);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST C# ASSIGNMENT', '2019-01-29 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND C# ASSIGNMENT', '2019-02-27 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'C#DB CONNECTOR ASSIGNMENT', '2019-03-26 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST C#-FRONT-END ASSIGNMENT', '2019-04-16 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND C#-FRONT-END ASSIGNMENT', '2019-05-28 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING C# WITH DATABASE', '2019-04-03 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'C# TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-06-26 20:00:00', 4);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST JAVA ASSIGNMENT', '2019-07-17 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND JAVA ASSIGNMENT', '2019-07-31 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'JAVADB CONNECTOR ASSIGNMENT', '2019-08-14 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST JAVA-FRONT-END ASSIGNMENT', '2019-08-28 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND JAVA-FRONT-END ASSIGNMENT', '2019-09-11 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING JAVA WITH DATABASE', '2019-08-14 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'JAVA TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-09-27 20:00:00', 5);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST JAVA ASSIGNMENT', '2019-07-31 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND JAVA ASSIGNMENT', '2019-08-28 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'JAVADB CONNECTOR ASSIGNMENT', '2019-09-25 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST JAVA-FRONT-END ASSIGNMENT', '2019-10-16 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND JAVA-FRONT-END ASSIGNMENT', '2019-11-27 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING JAVA WITH DATABASE', '2019-10-04 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'JAVA TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-12-27 20:00:00', 6);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST C# ASSIGNMENT', '2019-07-17 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND C# ASSIGNMENT', '2019-07-31 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'C#DB CONNECTOR ASSIGNMENT', '2019-08-14 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST C#-FRONT-END ASSIGNMENT', '2019-08-28 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND C#-FRONT-END ASSIGNMENT', '2019-09-11 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING C# WITH DATABASE', '2019-08-14 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'C# TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-09-27 20:00:00', 7);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 1', 'FIRST C# ASSIGNMENT', '2019-07-31 20:00:00', 8);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 2', 'SECOND C# ASSIGNMENT', '2019-08-28 20:00:00', 8);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 3', 'C#DB CONNECTOR ASSIGNMENT', '2019-09-25 20:00:00', 8);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 4', 'FIRST C#-FRONT-END ASSIGNMENT', '2019-10-16 20:00:00', 8);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('ASSIGNMENT 5', 'SECOND C#-FRONT-END ASSIGNMENT', '2019-11-27 20:00:00', 8);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('INDIVIDUAL PROJECT', 'INDIVIDUAL PROJECT BINDING C# WITH DATABASE', '2019-10-04 20:00:00', 8);
INSERT INTO ASSIGNMENT (TITLE, AS_DESCRIPTION, SUB_DATE_TIME, COURSE_ID) VALUES ('TEAM PROJECT', 'C# TEAM PROJECT BUILDING A WEB APPLICATION, EMPHASIZING ON TEAMWORK', '2019-12-27 20:00:00', 8);


-- DIORTHOSI STOIXEION STIN EISAGOGI
-- DELETE FROM ASSIGNMENT WHERE ASSIGNMENT_ID=3;
-- ALTER TABLE ASSIGNMENT AUTO_INCREMENT = 9;

-- ** INSERT STUDENT_COURSE VALUES **--
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (1, 1, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (1, 7, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (2, 1, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (3, 2, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (4, 3, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (5, 4, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (6, 5, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (7, 6, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (8, 2, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (8, 7, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (9, 7, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (10, 8, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (11, 1, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (12, 4, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (12, 6, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (13, 2, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (14, 3, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (15, 4, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (16, 5, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (17, 6, 2500);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (18, 7, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (19, 8, 2000);
INSERT INTO STUDENT_COURSE (STUDENT_ID, COURSE_ID, TUITION_FEES) VALUES (20, 1, 2500);

-- DIORTHOSI STOIXEION STIN EISAGOGI
-- DELETE FROM STUDENT_COURSE WHERE ST_CO_ID=2;
-- ALTER TABLE STUDENT_COURSE AUTO_INCREMENT = 1;

-- ** INSERT TRAINER_COURSE VALUES **--
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (1, 1, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (1, 2, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (1, 5, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (1, 6, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (2, 1, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (2, 2, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (2, 5, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (2, 6, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (3, 1, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (3, 2, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (3, 5, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (3, 6, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (4, 3, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (4, 1, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (4, 7, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (4, 5, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (5, 3, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (5, 3, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (5, 7, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (5, 7, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (6, 2, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (6, 3, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (6, 6, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (6, 7, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (7, 4, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (7, 4, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (7, 8, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (7, 8, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (8, 4, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (8, 4, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (8, 8, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (8, 8, 'DATABASES');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (9, 3, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (9, 4, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (9, 7, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (9, 8, 'FRONT END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (10, 1, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (10, 2, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (10, 5, 'BACK END');
INSERT INTO TRAINER_COURSE (TRAINER_ID, COURSE_ID, SUBJECT_TAUGHT) VALUES (10, 6, 'BACK END');

-- DIORTHOSI STOIXEION STIN EISAGOGI
-- DELETE FROM TRAINER_COURSE WHERE TR_CO_ID=2;
-- ALTER TABLE TRAINER_COURSE AUTO_INCREMENT = 1;



-- ** INSERT ASSIGNMENT_STUDENT VALUES **--

-- cb8 java full time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (1, 1, 20, 95);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (1, 2, 16, 80);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (1, 11, 8, 50);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (1, 20, 13, 65);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (2, 1, 20, 98);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (2, 2, 18, 82);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (2, 11, 10, 58);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (2, 20, 14, 75);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (3, 1, 19, 96);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (3, 2, 12, 68);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (3, 11, 17, 82);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (3, 20, 18, 85);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (4, 1, 18, 8);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (4, 2, 14, 74);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (4, 11, 14, 72);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (4, 20, 11, 64);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (5, 1, 20, 92);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (5, 2, 15, 75);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (5, 11, 12, 71);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (5, 20, 17, 80);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (6, 1, 15, 85);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (6, 2, 14, 77);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (6, 11, 14, 81);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (6, 20, 15, 84);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (7, 1, 18, 96);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (7, 2, 15, 83);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (7, 11, 16, 84);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (7, 20, 17, 88);

-- cb8 java part time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (8, 3, 15, 75);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (8, 8, 18, 91);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (8, 13, 14, 80);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (9, 3, 9, 74);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (9, 8, 13, 79);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (9, 13, 17, 87);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (10, 3, 15, 81);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (10, 8, 14, 83);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (10, 13, 10, 68);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (11, 3, 19, 97);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (11, 8, 20, 98);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (11, 13, 17, 93);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (12, 3, 16, 86);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (12, 8, 17, 81);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (12, 13, 14, 80);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (13, 3, 15, 78);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (13, 8, 17, 92);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (13, 13, 15, 85);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (14, 3, 16, 88);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (14, 8, 20, 96);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (14, 13, 18, 91);

-- cb8 csharp full time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (15, 4, 16, 71);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (15, 14, 12, 18);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (16, 4, 11, 59);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (16, 14, 16, 75);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (17, 4, 20, 96);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (17, 14, 7, 48);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (18, 4, 17, 86);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (18, 14, 15, 82);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (19, 4, 14, 74);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (19, 14, 19, 96);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (20, 4, 16, 83);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (20, 14, 10, 68);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (21, 4, 13, 66);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (21, 14, 18, 87);

-- cb8 csharp part time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (22, 5, 16, 76);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (22, 12, 18, 88);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (22, 15, 15, 81);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (23, 5, 20, 95);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (23, 12, 14, 78);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (23, 15, 12, 71);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (24, 5, 16, 76);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (24, 12, 17, 84);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (24, 15, 15, 79);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (25, 5, 16, 81);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (25, 12, 18, 88);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (25, 15, 13, 70);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (26, 5, 14, 78);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (26, 12, 17, 83);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (26, 15, 16, 90);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (27, 5, 12, 71);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (27, 12, 19, 93);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (27, 15, 18, 89);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (28, 5, 18, 84);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (28, 12, 15, 80);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (28, 15, 14, 71);

-- cb9 java full time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (29, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (29, 16, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (30, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (30, 16, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (31, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (31, 16, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (32, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (32, 16, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (33, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (33, 16, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (34, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (34, 16, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (35, 6, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (35, 16, NULL, NULL);

-- cb9 java part time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (36, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (36, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (36, 17, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (37, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (37, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (37, 17, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (38, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (38, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (38, 17, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (39, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (39, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (39, 17, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (40, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (40, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (40, 17, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (41, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (41, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (41, 17, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (42, 7, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (42, 12, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (42, 17, NULL, NULL);

-- cb9 csharp full time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (43, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (43, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (43, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (43, 18, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (44, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (44, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (44, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (44, 18, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (45, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (45, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (45, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (45, 18, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (46, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (46, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (46, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (46, 18, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (47, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (47, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (47, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (47, 18, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (48, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (48, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (48, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (48, 18, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (49, 1, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (49, 8, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (49, 9, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (49, 18, NULL, NULL);

-- cb9 csharp part time
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (50, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (50, 19, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (51, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (51, 19, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (52, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (52, 19, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (53, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (53, 19, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (54, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (54, 19, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (55, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (55, 19, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (56, 10, NULL, NULL);
INSERT INTO ASSIGNMENT_STUDENT (ASSIGNMENT_ID, STUDENT_ID, ORAL_MARK, TOTAL_MARK) VALUES (56, 19, NULL, NULL);

