USE PRIVATE_SCHOOL;

-- EKTIPOSI LISTAS COURSES
SELECT C.TITLE, C.STREAM, C.CO_TYPE, C.START_DATE, C.END_DATE
FROM COURSE C;

-- EKTIPOSI LISTAS STUDENTS (STO TOTALFEES BAZO TA SINOLIKA FEES TON MATHIMATON TOU)
SELECT S.LASTNAME, S.FIRSTNAME, S.DATEOFBIRTH, SUM(SC.TUITION_FEES) AS TOTALFEES
FROM STUDENT S, STUDENT_COURSE SC
WHERE S.STUDENT_ID=SC.STUDENT_ID
GROUP BY S.STUDENT_ID
ORDER BY LASTNAME ASC;

-- EKTIPOSI LISTAS TRAINERS (XORIS TA SUBJECTS POU EINAI MULTIVARIABLE)
SELECT T.FIRSTNAME, T.LASTNAME
FROM TRAINER T
ORDER BY T.LASTNAME;

-- EKTIPOSI LISTAS TRAINERS ME TA SUBJECTS KATHENOS (OSOI EXOUN POLLAPLA SUBJECTS EKTIPONONTAI ANTISTOIXES FORES)
SELECT DISTINCT T.LASTNAME, T.FIRSTNAME, TC.SUBJECT_TAUGHT AS SUBJECTS
FROM TRAINER T, TRAINER_COURSE TC
WHERE T.TRAINER_ID=TC.TRAINER_ID
ORDER BY T.LASTNAME ASC;

-- EKTIPOSI LISTAS ASSIGNMENTS
SELECT A.TITLE, A.AS_DESCRIPTION, A.SUB_DATE_TIME
FROM ASSIGNMENT A
ORDER BY A.ASSIGNMENT_ID;

-- EKTIPOSI LISTAS STUDENTS PER COURSE (PX GIA CB8 - C# - FULL TIME)
SELECT S.LASTNAME, S.FIRSTNAME, S.DATEOFBIRTH
FROM STUDENT S, STUDENT_COURSE SC, COURSE C
WHERE S.STUDENT_ID=SC.STUDENT_ID
AND SC.COURSE_ID=C.COURSE_ID
AND C.TITLE='CB8' && C.STREAM='C#' && C.CO_TYPE='FULL TIME'
ORDER BY LASTNAME ASC;

-- EKTIPOSI LISTAS TRAINERS PER COURSE (PX GIA CB8 - C# - PART TIME) ME TA SUBJECTS KATHENOS
SELECT T.LASTNAME, T.FIRSTNAME, TC.SUBJECT_TAUGHT
FROM TRAINER T, TRAINER_COURSE TC, COURSE C
WHERE T.TRAINER_ID=TC.TRAINER_ID
AND TC.COURSE_ID=C.COURSE_ID
AND C.TITLE='CB8' && C.STREAM='C#' && C.CO_TYPE='PART TIME'
ORDER BY T.LASTNAME ASC;

-- EKTIPOSI LISTAS TRAINERS PER COURSE (PX GIA CB8 - C# - PART TIME) XORIS TA SUBJECT
SELECT DISTINCT T.LASTNAME, T.FIRSTNAME
FROM TRAINER T, TRAINER_COURSE TC, COURSE C
WHERE T.TRAINER_ID=TC.TRAINER_ID
AND TC.COURSE_ID=C.COURSE_ID
AND C.TITLE='CB8' && C.STREAM='JAVA' && C.CO_TYPE='FULL TIME'
ORDER BY T.LASTNAME ASC;

-- EKTIPOSI LISTAS ASSIGNMENTS PER COURSE (PX GIA CB8 - C# - PART TIME)
SELECT A.TITLE, A.AS_DESCRIPTION, A.SUB_DATE_TIME
FROM ASSIGNMENT A, COURSE C
WHERE A.COURSE_ID=C.COURSE_ID
AND C.TITLE='CB8' && C.STREAM='C#' && C.CO_TYPE='PART TIME'
ORDER BY A.ASSIGNMENT_ID;

-- EKTIPOSI LISTAS ASSIGNMENTS PER COURSE PER STUDENT ME MARKS (PX GIA CB8 - JAVA - PART TIME  -  ANGELOS ANGELOU)
SELECT A.TITLE, A.AS_DESCRIPTION, A.SUB_DATE_TIME, SA.ORAL_MARK, SA.TOTAL_MARK
FROM STUDENT S, COURSE C, STUDENT_COURSE SC, ASSIGNMENT A, ASSIGNMENT_STUDENT SA
WHERE C.COURSE_ID=SC.COURSE_ID
AND S.STUDENT_ID=SC.STUDENT_ID
AND S.STUDENT_ID=SA.STUDENT_ID
AND A.ASSIGNMENT_ID=SA.ASSIGNMENT_ID
AND A.COURSE_ID=C.COURSE_ID
AND C.TITLE='CB8'&&C.STREAM='JAVA'&&C.CO_TYPE='FULL TIME'
AND S.LASTNAME='ANGELOU'&&S.FIRSTNAME='ANGELOS';

-- EKTIPOSI LISTAS ASSIGNMENTS PER COURSE PER STUDENT XORIS MARKS (PX GIA CB8 - JAVA - FULL TIME  -  ANGELOS ANGELOU)
SELECT A.TITLE, A.AS_DESCRIPTION, A.SUB_DATE_TIME
FROM STUDENT S, COURSE C, STUDENT_COURSE SC, ASSIGNMENT A, ASSIGNMENT_STUDENT SA
WHERE C.COURSE_ID=SC.COURSE_ID
AND S.STUDENT_ID=SC.STUDENT_ID
AND S.STUDENT_ID=SA.STUDENT_ID
AND A.ASSIGNMENT_ID=SA.ASSIGNMENT_ID
AND A.COURSE_ID=C.COURSE_ID
AND C.TITLE='CB8'&&C.STREAM='JAVA'&&C.CO_TYPE='FULL TIME'
AND S.LASTNAME='ANGELOU'&&S.FIRSTNAME='ANGELOS';

-- EKTIPOSI LISTAS STUDENTS POU EINAI EGGEGRAMMENOI SE PERISSOTERA APO ENA COURSES
SELECT S.LASTNAME, S.FIRSTNAME, S.DATEOFBIRTH, SUM(SC.TUITION_FEES) AS TOTALFEES
FROM STUDENT S, COURSE C, STUDENT_COURSE SC
WHERE S.STUDENT_ID=SC.STUDENT_ID
AND SC.COURSE_ID=C.COURSE_ID
GROUP BY S.STUDENT_ID
HAVING COUNT(*)>1
ORDER BY S.LASTNAME; 

